global:
  scrape_interval: 15s

rule_files:
  - "rules/*.yml"  # Make sure this file exists in the same directory

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']  # Update if Alertmanager runs on a different host

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: ['10.244.2.201:30080']

  - job_name: 'node'
    static_configs:
      - targets:
          - '172.31.36.143:9100'
          - '172.31.32.16:9100'
          - '172.31.37.85:9100'
